apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging
spec:
  replicas: 1                  # Number of replicas to start with
  selector:
    matchLabels:
      app: django-messaging
  template:
    metadata:
      labels:
        app: django-messaging
    spec:
      containers:
      - name: django-messaging
        image: your-dockerhub-username/messaging-app:latest  # Docker image for your Django app
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  type: ClusterIP               # Internal service only, not exposed to the internet
  selector:
    app: django-messaging
  ports:
    - protocol: TCP
      port: 8000                # Port exposed inside the cluster
      targetPort: 8000          # Container port the service points to
