apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      version: green
  template:
    metadata:
      labels:
        app: django
        version: green
    spec:
      containers:
      - name: django
        image: your-dockerhub-username/messaging-app:2.0   # Green version
        ports:
        - containerPort: 8000
