#!/bin/bash
# kubctl-0x01
# Script to scale Django app deployment and monitor it

DEPLOYMENT_NAME=django-messaging   # Name of the Kubernetes Deployment
REPLICAS=3                          # Number of replicas to scale to

# 1. Scale the deployment to the desired number of replicas
echo "Scaling deployment $DEPLOYMENT_NAME to $REPLICAS replicas..."
kubectl scale deployment $DEPLOYMENT_NAME --replicas=$REPLICAS

# 2. Verify that multiple pods are running
echo "Checking pods status..."
kubectl get pods

# 3. Monitor resource usage (requires metrics-server to be installed)
echo "Checking resource usage..."
kubectl top pods

# 4. Perform load testing using wrk
echo "Performing load test using wrk..."
wrk -t2 -c10 -d10s http://$SERVICE_IP:$PORT/