apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django          # This will select pods with label 'app=django'
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
