# Generated by Django 5.2.4 on 2025-07-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
