#!/bin/bash
# kurbeScript

if ! command -v minikube &> /dev/null
then
    echo "Minikube is not installed. Please install it first."
    exit 1
fi


minikube start

kubectl cluster-info

kubectl get pods -A
